apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-metrics-cronjob
  namespace: monitoring
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: node-metrics
            image: shanukumarm/node-metric-collector:0.0.4
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: metrics-volume
                mountPath: /metrics
          restartPolicy: OnFailure
          volumes:
            - name: metrics-volume
              persistentVolumeClaim:
                claimName: metrics-pvc
