apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: node-metrics-cronjob
spec:
  schedule: "*/1 * * * *" # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: node-metrics
            image: <your-docker-image>
            imagePullPolicy: IfNotPresent # Or use "Always" as per your need
          restartPolicy: OnFailure
