apiVersion: v1
kind: Pod
metadata:
  name: node-metrics-pod
  namespace: monitoring
spec:
  containers:
    - name: node-metrics
      image: shanukumarm/node-metric-collector:0.0.1
      volumeMounts:
        - name: metrics-volume
          mountPath: /metrics
  volumes:
    - name: metrics-volume
      persistentVolumeClaim:
        claimName: metrics-pvc
