persistentVolume:
  storage: 1Gi
  accessMode: ReadWriteOnce
  path: /persistent/metrics/node

persistentVolumeClaim:
  storage: 1Gi
  accessMode: ReadWriteOnce

cron:
  schedule: "*/1 * * * *"

image:
  repository: shanukumarm/node-metric-collector
  tag: 0.0.4
  pullPolicy: IfNotPresent

volumeMount:
  mountPath: /metrics

restartPolicy: OnFailure

namespace: monitoring
